# DataSource Config
spring:
  name: usercenter2Backend


  #接口文档配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #接口文档配置
  profiles:
    active: dev
  # 数据库地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leo22
    username: root
    password: 123456

  #session配置
  session:
    store-type: redis
    timeout: 86400

  #redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
# 服务端口
server:
  port: 8082
  servlet:
    context-path: /api
#mybatis-plus 配置
mybatis-plus:
  #配置逻辑删除
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #配置禁止默认驼峰转换下划线
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.usercenter2backend.mybatis.entity
## 应用服务 WEB 访问端口
#server.port=8080

