spring:
  # 数据库地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.40.32.60:3306/user_center
    username: dogyupi
    password: yupi666
# 失效时间：1天
session: 86400



##下面这些内容是为了让MyBatis映射
##指定Mybatis的Mapper文件
#mybatis.mapper-locations=classpath:mappers/*xml
##指定Mybatis的实体目录
#mybatis.type-aliases-package=com.example.usercenter2backend.mybatis.entity
## 应用服务 WEB 访问端口
#server.port=8080

